debug drone

diff --git a/.drone.yml b/.drone.yml
--- a/.drone.yml
+++ b/.drone.yml
@@ -1,7 +1,14 @@
 ---
 kind: pipeline
 type: docker
-name: build-pr
+name: build-pull-request
+
+trigger:
+  branches:
+    exclude:
+    - release-*
+  event:
+    - push
 
 platform:
   os: linux
@@ -70,3 +77,119 @@ steps:
   - upload_coverage
   - build_docs
   - build_plugin
+
+- name: report
+  image: srclosson/grafana-plugin-ci-alpine:latest
+  commands:
+  - ./node_modules/.bin/grafana-toolkit plugin:ci-report
+  depends_on:
+  - upload_coverage
+  - package
+
+- name: publish_artifacts_to_gcs
+  image: google/cloud-sdk
+  commands:
+  - apt update
+  - apt install -y jq git-lfs
+  - PLUGIN_NAME=`cat ci/dist/plugin.json|jq '.id'| sed s/\"//g`
+  - VERSION=`cat ci/dist/plugin.json|jq '.info.version'| sed s/\"//g`
+  - env
+  - if [ -z "${GCLOUD_SERVICE_KEY}" ]; then \
+      echo "Missing GCS Publish Key" \
+      exit -1 \
+    fi
+  - echo ${GCLOUD_SERVICE_KEY} | gcloud auth activate-service-account --key-file=-
+  - echo "Contents of artifacts"
+  - echo "Copying artifacts to ${PLUGIN_NAME}/${VERSION}/${DRONE_BRANCH}/${CIRCLE_SHA1}"
+  - echo gsutil -m cp -r ci/packages/** gs://integration-artifacts/${PLUGIN_NAME}/${VERSION}/${DRONE_BRANCH}/${DRONE_SHA1}
+  - echo gsutil rm -f gs://integration-artifacts/${PLUGIN_NAME}/${VERSION}/${DRONE_BRANCH}/latest/** || true
+  - echo "Copying artifacts to ${PLUGIN_NAME}/${VERSION}/${DRONE_BRANCH}/latest"
+  - echo gsutil -m cp -r ci/packages/** gs://integration-artifacts/${PLUGIN_NAME}/${VERSION}/${DRONE_BRANCH}/latest
+  - if [ ${CIRCLE_BRANCH} == "master" ]; then \
+      echo "Cleaning master latest" \
+      gsutil rm -f gs://integration-artifacts/${PLUGIN_NAME}/${DRONE_BRANCH}/latest/** || true \
+      echo "Copying artifacts to master latest" \
+      gsutil -m cp -r ci/packages/** gs://integration-artifacts/${PLUGIN_NAME}/${DRONE_BRANCH}/latest \
+    fi
+  - gsutil ls -r gs://integration-artifacts/${PLUGIN_NAME}
+  environment:
+    GCLOUD_SERVICE_KEY:
+      from_secret: gcloud_service_key
+  depends_on:
+  - package
+
+---
+kind: pipeline
+type: docker
+name: release
+
+trigger:
+  branches:
+    - release-*
+  event:
+    - promote
+
+steps:
+- name: publish_gcs_release
+  image: google/cloud-sdk
+  commands:
+  - apt update
+  - apt install -y jq git-lfs
+  - PLUGIN_NAME=`cat ci/dist/plugin.json|jq '.id'| sed s/\"//g`
+  - "echo \"Plugin Name: ${PLUGIN_NAME}\""
+  - VERSION=`cat ci/dist/plugin.json|jq '.info.version'| sed s/\"//g`
+  - "echo \"Plugin Version: ${VERSION}\""
+  - if [ -z "${GCLOUD_SERVICE_KEY}" ]; then \
+      echo "Missing GCS Publish Key" \
+      exit -1 \
+    fi
+  - echo ${GCLOUD_SERVICE_KEY} | gcloud auth activate-service-account --key-file=-
+  - echo "Contents of artifacts"
+  - echo "Copying artifacts to ${PLUGIN_NAME}/release/${VERSION}"
+  - if [ -d ci/packages/any ]; then \
+      gsutil -m cp -r ci/packages/any/** gs://integration-artifacts/${PLUGIN_NAME}/release/${VERSION}/any \
+    fi
+  environment:
+    GCLOUD_SERVICE_KEY:
+      from_secret: gcloud_service_key
+  when:
+    branch:
+    - release-*
+
+- name: publish_github_release
+  image: srclosson/grafana-plugin-ci-alpine:latest
+  commands:
+  - rm -rf $(yarn cache dir) && cp -r yarn-cache $(yarn cache dir)
+  - ./node_modules/.bin/grafana-toolkit plugin:github-publish
+  when:
+    branch:
+    - release-*
+
+---
+kind: pipeline
+type: docker
+name: publish
+
+trigger:
+  branches:
+    - release-*
+  event:
+    - promote
+
+steps:
+- name: publish_to_gcom
+  image: srclosson/grafana-plugin-ci-alpine:latest
+  commands:
+  - if [ -f ./node_modules/.bin/grafana-publisher ]; then \
+      ./node_modules/.bin/grafana-publisher validate \
+    fi
+  - apt update
+  - apt install -y jq git-lfs
+  - PLUGIN_NAME=`cat ci/dist/plugin.json|jq '.id'| sed s/\"//g`
+  - echo Plugin Name ${PLUGIN_NAME}
+  - VERSION=`cat ci/dist/plugin.json|jq '.info.version'| sed s/\"//g`
+  - echo Plugin Version ${VERSION}
+  - ./node_modules/.bin/grafana-publisher --auto publish ${PLUGIN_NAME} ${VERSION}
+  when:
+    branch:
+    - release-*
