update circleci and changelog

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -14,23 +14,6 @@ aliases:
     branches:
       only: /^v[1-9]*[0-9]+\.[1-9]*[0-9]+\.x$/
 
-workflows:
-  plugin_workflow:
-    jobs:
-      - build
-      - report:
-          requires:
-            - build
-      - approve_release:
-          type: approval
-          requires:
-            - report
-          filters: *filter-only-release
-      - publish_github_release:
-          requires:
-            - approve_release
-          filters: *filter-only-release
-
 executors:
   default_exec: # declares a reusable executor
     docker:
@@ -38,9 +21,65 @@ executors:
   e2e_exec:
     docker:
       - image: srclosson/grafana-plugin-ci-e2e:latest
+  circle_cli:
+    docker:
+      - image: circleci/circleci-cli:alpine
+  cloud_sdk_exec:
+    docker:
+      - image: google/cloud-sdk
+
+workflows:
+  plugin_workflow:
+    jobs:
+      - yarn_install
+      - build_docs:
+          requires:
+            - yarn_install
+      - build_frontend:
+          requires:
+            - yarn_install
+      - code_coverage_frontend:
+          requires:
+            - build_frontend
+      - upload_coverage:
+          requires:
+          - code_coverage_frontend
+      - package:
+          requires:
+          - build_frontend
+          - build_docs
+      - publish_artifacts_to_gcs:
+          requires:
+          - package
+      - report:
+          requires:
+          - package
+          - upload_coverage
+      - approve_release:
+          type: approval
+          requires:
+          - report
+          filters: *filter-only-release
+      - publish_gcs_release:
+          requires:
+            - approve_release
+          filters: *filter-only-release
+      - publish_github_release:
+          requires:
+          - approve_release
+          filters: *filter-only-release
+      - approve_publish_gcom:
+          type: approval
+          requires:
+          - publish_github_release
+          filters: *filter-only-release
+      - publish_to_gcom:
+          requires:
+          - approve_publish_gcom
+          filters: *filter-only-release
 
 jobs:
-  build:
+  yarn_install:
     executor: default_exec
     steps:
       - checkout
@@ -63,28 +102,85 @@ jobs:
           paths:
             - ~/.cache/Cypress
           key: cypress-cache-{{ .Environment.CACHE_VERSION }}-{{ checksum "yarn.lock" }}
+
+  build_docs:
+    executor: default_exec
+    steps:
+      - checkout
+      - restore_cache:
+          name: restore node_modules
+          keys:
+          - build-cache-{{ .Environment.CACHE_VERSION }}-{{ checksum "yarn.lock" }}
       - run:
-          name: Build and test panel 
-          command: /usr/local/bin/grafana-toolkit plugin:ci-build
-      - run:
-          name: Move results to ci folder
-          command: /usr/local/bin/grafana-toolkit plugin:ci-build --finish
-      - run:
-          name: Package distribution
+          name: Build docs
           command: |
-            /usr/local/bin/grafana-toolkit plugin:ci-package
+            ./node_modules/.bin/grafana-toolkit plugin:ci-docs
+            [ -d "dist" ] || circleci-agent step halt
       - persist_to_workspace:
           root: .
           paths:
-          - ci/jobs/package
-          - ci/packages
-          - ci/dist
-          - ci/grafana-test-env
-      - store_artifacts:
-          path: ci
+            - dist
 
-  report:
+  build_frontend:
     executor: default_exec
+    steps:
+      - checkout
+      - restore_cache:
+          name: restore node_modules
+          keys:
+          - build-cache-{{ .Environment.CACHE_VERSION }}-{{ checksum "yarn.lock" }}
+      - run:
+          name: Build and test frontend
+          command: |
+            ./node_modules/.bin/grafana-toolkit plugin:ci-build
+            ./node_modules/.bin/grafana-toolkit plugin:ci-build --finish
+      - persist_to_workspace:
+          root: .
+          paths:
+            - ci
+
+  code_coverage_frontend:
+    executor: default_exec
+    steps:
+    - checkout
+    - attach_workspace:
+        at: .
+    - restore_cache:
+        name: restore node_modules
+        keys:
+          - build-cache-{{ .Environment.CACHE_VERSION }}-{{ checksum "yarn.lock" }}
+    - run:
+        name: Run coverage report
+        command: |
+          /usr/local/bin/cc-test-reporter format-coverage -t lcov -o out/codeclimate.frontend.json ci/jobs/build_frontend/coverage/lcov.info
+    - run:
+        name: Install jest and jest-junit
+        command: yarn global add jest jest-junit
+    - run:
+        name: Run tests with JUnit as reporter
+        command: jest --ci --runInBand --reporters=default --reporters=jest-junit
+        environment:
+          JEST_JUNIT_OUTPUT_DIR: "test-results/jest/results.xml"
+    - persist_to_workspace:
+        root: .
+        paths:
+        - out
+        - ci/jobs/code_coverage_frontend
+    - store_test_results:
+        path: test-results
+
+  upload_coverage:
+    executor: default_exec
+    steps:
+      - attach_workspace:
+          at: .
+      - run:
+          name: Upload coverage results to Code Climate
+          command: |
+            /usr/local/bin/cc-test-reporter sum-coverage out/codeclimate.*.json -d -p 1 -o out/codeclimate.total.json
+            /usr/local/bin/cc-test-reporter upload-coverage -i out/codeclimate.total.json
+  package:
+    executor: e2e_exec
     steps:
       - checkout
       - attach_workspace:
@@ -94,11 +190,113 @@ jobs:
           keys:
             - build-cache-{{ .Environment.CACHE_VERSION }}-{{ checksum "yarn.lock" }}
       - run:
-          name: Toolkit report
+          name: Package Distribution (for signing/etc)
           command: |
-            /usr/local/bin/grafana-toolkit plugin:ci-report
+            #
+            # ci-package will create the zip file
+            #
+            ./node_modules/.bin/grafana-toolkit plugin:ci-package
+            #
+            #
+            PLUGIN_NAME=`cat ci/dist/plugin.json|jq '.id'| sed s/\"//g`
+            VERSION=`cat ci/dist/plugin.json|jq '.info.version'| sed s/\"//g`
+            echo "Plugin Name: ${PLUGIN_NAME}"
+            echo "Plugin Version: ${VERSION}"
+      - persist_to_workspace:
+          root: .
+          paths:
+            - ci/dist
+            - ci/jobs/package
+            - ci/packages
       - store_artifacts:
-          path: ci
+          path: ci/packages
+
+  report:
+    executor: default_exec
+    steps:
+    - checkout
+    - attach_workspace:
+        at: .
+    - restore_cache:
+        name: restore node_modules
+        keys:
+          - build-cache-{{ .Environment.CACHE_VERSION }}-{{ checksum "yarn.lock" }}
+    - run:
+        name: Toolkit report
+        command: |
+          ./node_modules/.bin/grafana-toolkit plugin:ci-report
+    - store_artifacts:
+        path: ci
+
+  publish_artifacts_to_gcs:
+    executor: cloud_sdk_exec
+    steps:
+      - checkout
+      - attach_workspace:
+          at: .
+      - run:
+          name: "Copy Artifacts to GCP Bucket"
+          command: |
+            ls -l ci/jobs/build_frontend/dist/plugin.json
+            echo "Contents of ci/jobs/build_frontend/dist/plugin.json"
+            cat ci/jobs/build_frontend/dist/plugin.json
+            ls -lR ci/packages
+            apt update
+            apt install -y jq git-lfs
+            PLUGIN_NAME=`cat ci/dist/plugin.json|jq '.id'| sed s/\"//g`
+            echo "Plugin Name: ${PLUGIN_NAME}"
+            VERSION=`cat ci/dist/plugin.json|jq '.info.version'| sed s/\"//g`
+            echo "Plugin Version: ${VERSION}"
+            # copy
+            if [ -z "${GCLOUD_SERVICE_KEY}" ]; then
+              echo "Missing GCS Publish Key"
+              exit -1
+            fi
+            echo ${GCLOUD_SERVICE_KEY} | gcloud auth activate-service-account --key-file=-
+            echo "Contents of artifacts"
+            echo "Copying artifacts to ${PLUGIN_NAME}/${VERSION}/${CIRCLE_BRANCH}/${CIRCLE_SHA1}"
+            gsutil -m cp -r ci/packages/** gs://integration-artifacts/${PLUGIN_NAME}/${VERSION}/${CIRCLE_BRANCH}/${CIRCLE_SHA1}
+            echo "Cleaning latest"
+            gsutil rm -f gs://integration-artifacts/${PLUGIN_NAME}/${VERSION}/${CIRCLE_BRANCH}/latest/** || true
+            echo "Copying artifacts to ${PLUGIN_NAME}/${VERSION}/${CIRCLE_BRANCH}/latest"
+            gsutil -m cp -r ci/packages/** gs://integration-artifacts/${PLUGIN_NAME}/${VERSION}/${CIRCLE_BRANCH}/latest
+            # special handling for master
+            if [ ${CIRCLE_BRANCH} == "master" ]; then
+              echo "Cleaning master latest"
+              gsutil rm -f gs://integration-artifacts/${PLUGIN_NAME}/${CIRCLE_BRANCH}/latest/** || true
+              echo "Copying artifacts to master latest"
+              gsutil -m cp -r ci/packages/** gs://integration-artifacts/${PLUGIN_NAME}/${CIRCLE_BRANCH}/latest
+            fi
+            gsutil ls -r gs://integration-artifacts/${PLUGIN_NAME}
+
+  publish_gcs_release:
+    executor: cloud_sdk_exec
+    steps:
+      - checkout
+      - attach_workspace:
+          at: .
+      - run:
+          name: "Copy Artifacts to GCP Release Bucket"
+          command: |
+            ls -l ci/jobs/build_frontend/dist/plugin.json
+            echo "Contents of ci/jobs/build_frontend/dist/plugin.json"
+            cat ci/jobs/build_frontend/dist/plugin.json
+            ls -lR ci/packages
+            apt update
+            apt install -y jq git-lfs
+            PLUGIN_NAME=`cat ci/dist/plugin.json|jq '.id'| sed s/\"//g`
+            echo "Plugin Name: ${PLUGIN_NAME}"
+            VERSION=`cat ci/dist/plugin.json|jq '.info.version'| sed s/\"//g`
+            echo "Plugin Version: ${VERSION}"
+            # copy
+            if [ -z "${GCLOUD_SERVICE_KEY}" ]; then
+              echo "Missing GCS Publish Key"
+              exit -1
+            fi
+            echo ${GCLOUD_SERVICE_KEY} | gcloud auth activate-service-account --key-file=-
+            echo "Contents of artifacts"
+            echo "Copying artifacts to ${PLUGIN_NAME}/${VERSION}/${CIRCLE_BRANCH}/${CIRCLE_SHA1}"
+            gsutil -m cp -r ci/packages/** gs://integration-artifacts/${PLUGIN_NAME}/release/${VERSION}
 
   publish_github_release:
     executor: default_exec
@@ -106,7 +304,7 @@ jobs:
       - checkout
       - add_ssh_keys:
           fingerprints:
-            - "${GITHUB_SSH_FINGERPRINT}"
+          - << pipeline.parameters.ssh-fingerprint >>
       - attach_workspace:
           at: .
       - restore_cache:
@@ -116,4 +314,26 @@ jobs:
       - run:
           name: "Publish Release on GitHub"
           command: |
-            /usr/local/bin/grafana-toolkit plugin:github-publish
+            ./node_modules/.bin/grafana-toolkit plugin:github-publish
+
+  publish_tp_gcom:
+    executor: default_exec
+    steps:
+      - checkout
+      - add_ssh_keys:
+          fingerprints:
+          - << pipeline.parameters.ssh-fingerprint >>
+      - attach_workspace:
+          at: .
+      - restore_cache:
+          name: restore node_modules
+          keys:
+          - build-cache-{{ .Environment.CACHE_VERSION }}-{{ checksum "yarn.lock" }}
+      - run:
+          name: "Validate Environment Variables"
+          command: |
+            ./node_modules/.bin/grafana-publisher validate
+      - run:
+          name: "Publish Plugin to grafana.com"
+          command: |
+            ./node_modules/.bin/grafana-publisher --dryrun --auto publish
